---
name: Lint Code Base
on:
  pull_request: ~
  push:
    branches:
      - main

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint Code Base
        uses: mrcjkb/lua-typecheck-action@v0.2.0
        with:
          configpath: ".luarc.json"
          directories: "."
