#! /Users/shrik450/.asdf/installs/ruby/3.3.0/bin/ruby --disable=gems

require_relative "stacking"

cwindow = current_window
if has_window_left? cwindow
  yabai "window --focus west"
elsif window_in_stack? cwindow
  fwcs = first_window_of_current_stack
  if fwcs["id"] == cwindow["id"]
    yabai "window --focus west"
  else
    yabai "window --focus stack.prev"
  end
else
  yabai "window --focus west"
end
