#! /Users/shrik450/.asdf/shims/ruby --disable=gems

require_relative "stacking"

cwindow = current_window
if has_window_right? cwindow
  yabai "window --focus east"
elsif window_in_stack? cwindow
  lwcs = last_window_of_current_stack
  if lwcs["id"] == cwindow["id"]
    yabai "window --focus east"
  else
    yabai "window --focus stack.next"
  end
else
  yabai "window --focus east"
end