#! /usr/bin/env -S mise exec ruby@3.3 -- ruby --disable=gems

require_relative "stacking"

cwindow = current_window
if has_window_below? cwindow
  yabai "window --focus south"
elsif window_in_stack? cwindow
  lwcs = last_window_of_current_stack
  if lwcs["id"] == cwindow["id"]
    yabai "window --focus south"
  else
    yabai "window --focus stack.next"
  end
else
  yabai "window --focus south"
end
