#! /usr/bin/env -S mise exec ruby@3.3 -- ruby --disable=gems

require_relative "stacking"

cwindow = current_window
if has_window_above? cwindow
  yabai "window --focus north"
elsif window_in_stack? cwindow
  fwcs = first_window_of_current_stack
  if fwcs["id"] == cwindow["id"]
    yabai "window --focus north"
  else
    yabai "window --focus stack.prev"
  end
else
  yabai "window --focus north"
end
